version: '2'
services:
   db:
     image: postgres:13
     container_name: movies_admin_db
     volumes:
       - postgres:/var/lib/postgresql/data
       - ./postgres/movies_database.sql:/docker-entrypoint-initdb.d/movies_database.sql
     env_file:
       - ./config/env_db

   service:       
       build: 
           context: tasks
       env_file:
         - ./config/env_app
       depends_on:
         - db
       container_name: movies_admin_app

   nginx:
    image: nginx:1.21.4
    volumes:
      - ./src/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./src/app.conf:/etc/nginx/conf.d/default.conf:ro
      - services:/services
    container_name: app_nginx
    depends_on:
      - service
    ports:
      - "81:80"

   elastic_helper:
    build: postgres_to_es/
    env_file:
      - ./config/env_elastic
    container_name: elastic_helper
    volumes:
      - postgres_to_es:/elastic_helper
    depends_on:
      - elastic
      - db

   elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: app_elastics
    ports:
      - "9200:9200"
    depends_on:
      - db
    environment:
      - "discovery.type=single-node"



volumes:
  postgres:
  static:
  postgres_to_es:

